---
apiVersion: batch/v1
kind: Job
metadata:
  namespace: temp
  name: createchannel
spec:
  backoffLimit: 1
  template:
    metadata:
      name: createchannel
    spec:
      restartPolicy: "Never"
      volumes:
        - name: nfs
          persistentVolumeClaim:
            claimName: nfs-pvc-temp
      containers:
      - name: createchanneltx
        image: hyperledger/fabric-tools:1.2.1
        imagePullPolicy: Always
        command: ["sh", "-c", "cd /shared && pwd && ls && export FABRIC_CFG_PATH=$PWD && configtxgen -profile FourOrgsChannel -outputCreateChannelTx ${CHANNEL_NAME}.tx -channelID ${CHANNEL_NAME} && touch /shared/status_channeltx_complete "]
        env:
        - name: CHANNEL_NAME
          value: channel1
        - name: GODEBUG
          value: "netdns=go"
        volumeMounts:
        - mountPath: /shared
          name: nfs

      - name: createchannel
        image: hyperledger/fabric-tools:1.2.1
        env:
        - name: CHANNEL_NAME
          value: channel1
        - name: ORDERER_URL
          value: orderer.example-com:7050
        - name: CORE_VM_ENDPOINT
          value: "unix:///host/var/run/docker.sock"
        - name: GOPATH
          value: "/opt/gopath"
        - name: FABRIC_LOGGING_SPEC
          value: "DEBUG"
        - name: CORE_PEER_ID
          value: "cli"
        - name: CORE_PEER_TLS_ENABLED
          value: "true"
        - name: CORE_PEER_TLS_CERT_FILE
          value: "/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/peerOrganizations/org1-example-com/peers/peer0.org1-example-com/tls/server.crt"
        - name: CORE_PEER_TLS_KEY_FILE
          value: "/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/peerOrganizations/org1-example-com/peers/peer0.org1-example-com/tls/server.key"
        - name: CORE_PEER_TLS_ROOTCERT_FILE
          value: "/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/peerOrganizations/org1-example-com/peers/peer0.org1-example-com/tls/ca.crt"
        - name: CORE_PEER_MSPCONFIGPATH
          value: "/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/peerOrganizations/org1-example-com/users/Admin@org1-example-com/msp"
        - name: CORE_PEER_ADDRESS
          value: "peer0.org1-example-com:7051"
        - name: CORE_PEER_LOCALMSPID
          value: "Org1MSP"
        workingDir: /opt/gopath/src/github.com/hyperledger/fabric/peer
        command: ["sh", "-c", "while [ ! -f /shared/status_channeltx_complete ]; do echo Waiting for channeltx; sleep 2; done; peer channel create -o ${ORDERER_URL} -c ${CHANNEL_NAME} -f /shared/${CHANNEL_NAME}.tx --tls --cafile  /opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/ordererOrganizations/example-com/orderers/orderer.example-com/msp/tlscacerts/tlsca.example-com-cert.pem && rm /shared/status_channeltx_complete && touch /shared/status_channelcreate_complete"]
        volumeMounts:
         - mountPath: /opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/
           name: nfs
           subPath: crypto-config
         - mountPath: /shared/
           name: nfs
