---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  namespace: example-com
  name: orderer
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: hyperledger
        role: orderer
        org: orderer-org
        orderer-id: orderer
    spec:
      containers:
      - name: orderer
        image: hyperledger/fabric-orderer:latest
        env:
        - name: ORDERER_GENERAL_LOGLEVEL
          value: debug
        - name: ORDERER_GENERAL_LISTENADDRESS
          value: 0.0.0.0
        - name: ORDERER_GENERAL_GENESISMETHOD
          value: file
        - name: ORDERER_GENERAL_GENESISFILE
          value: /var/hyperledger/orderer/genesis.block
        - name: ORDERER_GENERAL_LOCALMSPID
          value: OrdererMSP
        - name: ORDERER_GENERAL_LOCALMSPDIR
          value: /var/hyperledger/orderer/msp
        - name: ORDERER_GENERAL_TLS_ENABLED
          value: "true"
        - name: ORDERER_GENERAL_TLS_PRIVATEKEY
          value: /var/hyperledger/orderer/tls/server.key
        - name: ORDERER_GENERAL_TLS_CERTIFICATE
          value: /var/hyperledger/orderer/tls/server.crt
        - name: ORDERER_GENERAL_TLS_ROOTCAS
          value: '[/var/hyperledger/orderer/tls/ca.crt]'
        - name: ORDERER_KAFKA_RETRY_SHORTINTERVAL
          value: "1s"
        - name: ORDERER_KAFKA_RETRY_SHORTTOTAL
          value: "30s"
        - name: ORDERER_KAFKA_VERBOSE
          value: "true"
        workingDir: /opt/gopath/src/github.com/hyperledger/fabric
        command: ["orderer"]
        volumeMounts:
         - mountPath: /var/hyperledger/orderer/msp
           name: nfs
           subPath: crypto-config/ordererOrganizations/example-com/orderers/orderer.example-com/msp
         - mountPath: /var/hyperledger/orderer/tls
           name: nfs
           subPath: crypto-config/ordererOrganizations/example-com/orderers/orderer.example-com/tls
         - mountPath: /var/hyperledger/orderer
           name: nfs
        ports:
         - containerPort: 7050
      volumes:
        - name: nfs
          persistentVolumeClaim:
            claimName: nfs-pvc-example-com
